# Generated by Django 5.1.2 on 2024-10-26 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicesapp', '0001_initial'),
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=200)),
                ('priority', models.IntegerField(choices=[(1, 'Immediately'), (2, 'High'), (3, 'Medium'), (4, 'Low')])),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Assigned'), (3, 'Canceled'), (4, 'Finished')], null=True)),
                ('issuetime', models.DateTimeField(auto_now_add=True)),
                ('dispatchtime', models.DateTimeField(blank=True, null=True)),
                ('closetime', models.DateTimeField(null=True)),
                ('solver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usersapp.userprofilemodel')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicesapp.servicemodel')),
                ('todepartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicesapp.departmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('dateofcomment', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usersapp.userprofilemodel')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsapp.ticketmodel')),
            ],
        ),
    ]
